### ISSUE TITLE
Error: Function converted via 'toJS'

### ISSUE THREAD

**Issue by rmasarovic** [flutter-webrtc/dart-webrtc#55]
Hi when update flutter to  Flutter  3.27.0 , i have multiple error with  Error: Function converted via 'toJS'.
for example
`media_stream_track_impl.dart:13:68: Error: Function converted via 'toJS' contains invalid types in its function signature: '*dynamic* Function(*dynamic*)'.`

**Comment by qqtb** [comment]
https://github.com/flutter-webrtc/dart-webrtc/pull/54/commits/f27d27c7af41ceeebe31b295af4fb38e7b4d793e fixes this for me.

so for the time being i use:

```
dependency_overrides:
  dart_webrtc:
    git:
      url: https://github.com/flutter-webrtc/dart-webrtc.git
      ref: f27d27c7af41ceeebe31b295af4fb38e7b4d793e
```
